### ISSUE TITLE
Xpath have been changed and selenium have much easier approach

### ISSUE THREAD

**Issue by dev-Yashwant** [missuo/GmailValidChecker#2]
in - GmailChecker/GmailCheckerEnhanced.py

`def startVerify(driver, emailPrefix):
	driver.get("https://accounts.google.com/signup/v2/webcreateaccount?biz=false&cc=JP&continue=https%3A%2F%2Fmyaccount.google.com%2F%3Fnlr%3D1&dsh=S2013611188%3A1665547988680440&flowEntry=SignUp&flowName=GlifWebSignIn&hl=en&service=accountsettings&authuser=0")
	driver.find_element('xpath','//*[@id="username"]').send_keys(emailPrefix)
	driver.find_element('xpath', '//*[@id="passwd"]/div[1]/div/div[1]/input').send_keys('ehihwihewq')
	time.sleep(5)
	result = driver.find_element('xpath','//*[@id="view_container"]/div/div/div[2]/div/div[1]/div/form/span/section/div/div/div[2]/div[1]/div/div[2]/div[2]').is_displayed()
	return result`
All xpath have been changed and we can use a simple approch to do this assing me to fix thanks

**Comment by missuo** [comment]
You've fixed it yourself haven't you? If so, you can submit a PR

**Comment by dev-Yashwant** [comment]
I will create PR, I have fixed it!

**Comment by dev-Yashwant** [comment]
#3 Check out updated version !
